
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 403)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 60, 601, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.button = QtWidgets.QPushButton(self.tab, clicked = lambda: self.clicked())
        self.button.setGeometry(QtCore.QRect(210, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.button.setFont(font)
        self.button.setObjectName("button")
        self.type = QtWidgets.QLineEdit(self.tab)
        self.type.setGeometry(QtCore.QRect(50, 50, 271, 41))
        self.type.setObjectName("type")
        self.date = QtWidgets.QLineEdit(self.tab)
        self.date.setGeometry(QtCore.QRect(50, 140, 271, 41))
        self.date.setObjectName("date")
        self.amount = QtWidgets.QLineEdit(self.tab)
        self.amount.setGeometry(QtCore.QRect(370, 100, 171, 41))
        self.amount.setObjectName("amount")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(370, 80, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 120, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lastLabel = QtWidgets.QLabel(self.tab)
        self.lastLabel.setGeometry(QtCore.QRect(280, 260, 47, 13))
        self.lastLabel.setText("")
        self.lastLabel.setObjectName("lastLabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.list = QtWidgets.QListWidget(self.tab_2)
        self.list.setGeometry(QtCore.QRect(30, 40, 531, 241))
        self.list.setObjectName("list")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 0, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button.setText(_translate("Dialog", "Enter"))
        self.label_2.setText(_translate("Dialog", "Type of Expenses(Products/Bill/Taxes)"))
        self.label_3.setText(_translate("Dialog", "Expenses Amount"))
        self.label_4.setText(_translate("Dialog", "Date to Pay"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Expenses"))
        self.label_5.setText(_translate("Dialog", "List of Expenses"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "List of Expenses"))
        self.label.setText(_translate("Dialog", "Expenses Monitoring System"))

        type = []
        date = []
        amount = []
        
    def clicked(self):
        type = self.type.text()
        date = self.date.text()
        amount = self.amount.text()

        self.list.addItem("Type of Expenses: " + type + " - Date to Pay: " + date + " - Amount to Pay: " + amount)
        self.date.setText("")
        self.type.setText("")
        self.amount.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
