
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 507)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(250, 10, 371, 481))
        self.listWidget.setObjectName("listWidget")
        self.delete_button = QtWidgets.QPushButton(Dialog, clicked = lambda: self.delete())
        self.delete_button.setGeometry(QtCore.QRect(540, 20, 75, 23))
        self.delete_button.setObjectName("delete_button")
        self.lastname = QtWidgets.QLineEdit(Dialog)
        self.lastname.setGeometry(QtCore.QRect(20, 30, 221, 41))
        self.lastname.setObjectName("lastname")
        self.firstname = QtWidgets.QLineEdit(Dialog)
        self.firstname.setGeometry(QtCore.QRect(20, 110, 221, 41))
        self.firstname.setObjectName("firstname")
        self.middlename = QtWidgets.QLineEdit(Dialog)
        self.middlename.setGeometry(QtCore.QRect(20, 180, 221, 41))
        self.middlename.setObjectName("middlename")
        self.section = QtWidgets.QLineEdit(Dialog)
        self.section.setGeometry(QtCore.QRect(90, 250, 151, 41))
        self.section.setObjectName("section")
        self.gender = QtWidgets.QLineEdit(Dialog)
        self.gender.setGeometry(QtCore.QRect(150, 320, 91, 41))
        self.gender.setObjectName("gender")
        self.age = QtWidgets.QLineEdit(Dialog)
        self.age.setGeometry(QtCore.QRect(150, 390, 91, 41))
        self.age.setObjectName("age")
        self.button = QtWidgets.QPushButton(Dialog, clicked = lambda: self.clicked())
        self.button.setGeometry(QtCore.QRect(100, 460, 75, 23))
        self.button.setObjectName("button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 230, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 300, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(150, 370, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CLASS RECORD"))
        self.delete_button.setText(_translate("Dialog", "PushButton"))
        self.button.setText(_translate("Dialog", "Enter"))
        self.label.setText(_translate("Dialog", "Lastname"))
        self.label_2.setText(_translate("Dialog", "Firstname"))
        self.label_3.setText(_translate("Dialog", "Middlename"))
        self.label_4.setText(_translate("Dialog", "Section"))
        self.label_5.setText(_translate("Dialog", "Gender"))
        self.label_6.setText(_translate("Dialog", "Age"))

        listWidget = []

    def clicked(self):
        lastname = self.lastname.text()
        firstname = self.firstname.text()
        middlename = self.middlename.text()
        section = self.section.text()
        age = self.age.text()
        gender = self.gender.text()

        self.listWidget.addItem(lastname + ", " + firstname + ", " + middlename + ", " + gender + ", " + section + ", " + age)
        
        self.lastname.setText("")
        self.firstname.setText("")
        self.middlename.setText("")
        self.section.setText("")
        self.age.setText("")
        self.gender.setText("")

    def delete(self):
        toDelete = self.listWidget.currentRow()
        self.listWidget.takeItem(toDelete)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
